[package]
name = "knowtilus"
version = "0.1.0"
edition = "2021"

[dependencies]
kd-tree = "0.6.0"
lopdf = "0.34.0"
rust-bert = { version = "0.23.0", features = ["download-libtorch"] }
tokio = "1.42.0"
