[package]
name = "knowtilus"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros", "time"] }
anyhow = "1.0.98"
pdf-extract = "0.9.0"